### ISSUE TITLE
No help text when using alias to channel where player has not joined 

### ISSUE THREAD

**Issue by S-S-X** [mt-mods/beerchat#100]
```bash
/cc #alias
/cc #channel
/channel-alias #alias #channel
/lc #alias
/lc #channel
#channel Hello world!
You need to join this channel in order to be able to send messages to it
#alias Hello world!
```

Last command should also show message about need to join channel before sending messages.

**Comment by SwissalpS** [comment]
in this example user left both channels. Even if he was still on #alias then I don't think he needs an error message for that channel as he was trying to post on #channel.  
However, if user is joined to #alias and not to #channel, there needn't be any message at all, since he is on one of the channels.

**Comment by S-S-X** [comment]
> in this example user left both channels. Even if he was still on #alias then I don't think he needs an error message for that channel as he was trying to post on #channel.
> However, if user is joined to #alias and not to #channel, there needn't be any message at all, since he is on one of the channels.

This one is fairly easy: user actually cannot be exclusively on #alias or #channel, actually he'll be on both or neither.

Thing is chat will be completely silent without any feedback if he has not joined and tries to use alias name as target, feedback/error message is only shown if he knows and uses real channel name.
